# Generated by Django 5.2 on 2025-05-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_slug_alter_articletranslation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='article',
            name='font_size',
            field=models.CharField(choices=[('small', 'Pequeno'), ('medium', 'Médio'), ('large', 'Grande')], default='medium', max_length=10, verbose_name='Tamanho da fonte'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.URLField(blank=True, null=True, verbose_name='Fonte'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='articles.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='content',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
