services:
  - type: web
    name: biospace
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn biospace_site.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: biospace_site.settings
      - key: SECRET_KEY
        value: your_secret_key
      - key: DATABASE_URL
        value: your_supabase_connection_string
      # coloque outras variáveis aqui
